server.port=8001

server.servlet.encoding.enabled= true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.application.name=SAA-18AALBaiLian

spring.ai.dashscope.api-key=${aiQwen_key}
##spring.ai.ollama.base-url=http://localhost:11434
##spring.ai.ollama.chat.model=qwen2.5:7b
spring.ai.dashscope.agent.options.app-id=b6de9996304645d89b074431d703536c
